#MOSTRAR TODOS REGISTROS / FILAS DE UNA TABLA#
SELECT email, nombre, apellidos FROM usuarios;

#MOSTRAR TODOS LOS CAMPOS#
SELECT * FROM usuarios;

#OPERADORES ARITMETICOS#
SELECT email, (7+7) AS 'OPERACION' FROM usuarios;

#FUNCIONES MATEMATICAS#
SELECT CEIL(7.34) AS 'OPERACION' FROM usuarios;